export const STATIC_MARKDOWN_RENDER_PLACEHOLDER_DELAY_MS = 220;
export const STATIC_MARKDOWN_RENDER_READY_MIN_HEIGHT = 2;
export const STATIC_MARKDOWN_RENDER_PLACEHOLDER_PULSE_MS = 900;
export const STATIC_MARKDOWN_RENDER_PLACEHOLDER_MIN_OPACITY = 0.45;
export const STATIC_MARKDOWN_RENDER_PLACEHOLDER_MAX_OPACITY = 1;
