import { Typography } from '@/constants/Typography';
import { StyleSheet } from 'react-native-unistyles';
import {
    DESKTOP_SIDEBAR_CHROME_BRAND_ROW_MIN_HEIGHT_PX,
    DESKTOP_SIDEBAR_CHROME_CONTROL_GAP_PX,
    DESKTOP_SIDEBAR_CHROME_HORIZONTAL_PADDING_PX,
    DESKTOP_SIDEBAR_CHROME_ROW_GAP_PX,
    DESKTOP_SIDEBAR_CHROME_TOP_ICON_GAP_PX,
    DESKTOP_SIDEBAR_CHROME_TOP_NAV_ICON_BUTTON_SIZE_PX,
    DESKTOP_SIDEBAR_CHROME_TOP_NAV_ICON_DISABLED_OPACITY,
    DESKTOP_SIDEBAR_CHROME_TOP_NAV_ICON_GLYPH_SIZE_PX,
    DESKTOP_SIDEBAR_CHROME_TOP_NAV_ICON_OPACITY,
    DESKTOP_SIDEBAR_CHROME_TOP_NOTIFICATION_DOT_RIGHT_PX,
    DESKTOP_SIDEBAR_CHROME_TOP_NOTIFICATION_DOT_SIZE_PX,
    DESKTOP_SIDEBAR_CHROME_TOP_NOTIFICATION_DOT_TOP_PX,
    DESKTOP_SIDEBAR_CHROME_TOP_PADDING_PX,
    DESKTOP_SIDEBAR_CHROME_TOP_SETTINGS_ICON_BUTTON_SIZE_PX,
    DESKTOP_SIDEBAR_CHROME_TOP_SETTINGS_ICON_OPACITY,
    DESKTOP_SIDEBAR_CHROME_WINDOW_CONTROLS_GAP_PX,
    DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX,
    DESKTOP_WINDOW_CONTROLS_SLOT_MIN_WIDTH_PX,
} from './desktopChromeMetrics';

export const desktopSidebarChromeStyles = StyleSheet.create((theme) => ({
    header: {
        flexDirection: 'column',
        alignItems: 'stretch',
        paddingHorizontal: DESKTOP_SIDEBAR_CHROME_HORIZONTAL_PADDING_PX,
        paddingTop: DESKTOP_SIDEBAR_CHROME_TOP_PADDING_PX,
        paddingBottom: DESKTOP_SIDEBAR_CHROME_CONTROL_GAP_PX / 2,
        backgroundColor: theme.colors.background.canvas,
        position: 'relative',
        zIndex: 100,
        overflow: 'visible',
        gap: DESKTOP_SIDEBAR_CHROME_ROW_GAP_PX,
    },
    windowControlsRow: {
        minHeight: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: DESKTOP_SIDEBAR_CHROME_WINDOW_CONTROLS_GAP_PX,
        position: 'relative',
        width: '100%',
    },
    utilityRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESKTOP_SIDEBAR_CHROME_TOP_ICON_GAP_PX,
        marginLeft: 'auto',
        position: 'relative',
        zIndex: 1,
    },
    windowControlsHost: {
        flexShrink: 0,
        minWidth: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_WIDTH_PX,
        alignItems: 'flex-start',
        justifyContent: 'center',
        position: 'relative',
        zIndex: 1,
    },
    contentRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESKTOP_SIDEBAR_CHROME_CONTROL_GAP_PX,
    },
    compactContentRow: {
        minHeight: DESKTOP_SIDEBAR_CHROME_BRAND_ROW_MIN_HEIGHT_PX,
    },
    brandGroup: {
        flexGrow: 1,
        flexShrink: 1,
        flexBasis: 0,
        minWidth: 0,
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESKTOP_SIDEBAR_CHROME_CONTROL_GAP_PX,
    },
    brandButton: {
        width: 32,
        minHeight: DESKTOP_SIDEBAR_CHROME_BRAND_ROW_MIN_HEIGHT_PX,
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    updateIndicatorHost: {
        flexShrink: 0,
        alignItems: 'center',
        justifyContent: 'center',
    },
    windowControlsSlot: {
        minWidth: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_WIDTH_PX,
        minHeight: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX,
        position: 'relative',
        justifyContent: 'center',
    },
    windowControlsContent: {
        minHeight: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    windowDragRegion: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX / 2,
    },
    titleContainerLeft: {
        flexGrow: 1,
        flexShrink: 1,
        flexBasis: 0,
        minWidth: 0,
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'center',
        overflow: 'visible',
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        flexShrink: 1,
        minWidth: 0,
        maxWidth: '100%',
    },
    titleText: {
        flexShrink: 1,
        fontSize: 18,
        lineHeight: 24,
        color: theme.colors.chrome.header.foreground,
        ...Typography.default('semiBold'),
    },
    statusControlWrapper: {
        alignSelf: 'stretch',
        flexShrink: 1,
        minWidth: 0,
        maxWidth: '100%',
    },
    envBadge: {
        marginTop: -4,
        marginLeft: -4,
        paddingHorizontal: 4,
        paddingVertical: 1,
        borderRadius: 999,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.base,
    },
    envBadgeText: {
        fontSize: 6,
        lineHeight: 8,
        color: theme.colors.text.secondary,
        ...Typography.default('semiBold'),
    },
    rightContainer: {
        flexShrink: 0,
        marginLeft: 'auto',
        alignItems: 'center',
        flexDirection: 'row',
        gap: 4,
    },
    iconButton: {
        width: 32,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    trailingIconButton: {
        width: 24,
        height: 32,
        alignItems: 'flex-end',
        justifyContent: 'center',
    },
    topIconButton: {
        width: DESKTOP_SIDEBAR_CHROME_TOP_NAV_ICON_BUTTON_SIZE_PX,
        height: DESKTOP_SIDEBAR_CHROME_TOP_NAV_ICON_BUTTON_SIZE_PX,
        alignItems: 'center',
        justifyContent: 'center',
        opacity: DESKTOP_SIDEBAR_CHROME_TOP_NAV_ICON_OPACITY,
    },
    topIconButtonDisabled: {
        opacity: DESKTOP_SIDEBAR_CHROME_TOP_NAV_ICON_DISABLED_OPACITY,
    },
    topSettingsIconButton: {
        width: DESKTOP_SIDEBAR_CHROME_TOP_SETTINGS_ICON_BUTTON_SIZE_PX,
        height: DESKTOP_SIDEBAR_CHROME_TOP_SETTINGS_ICON_BUTTON_SIZE_PX,
        alignItems: 'center',
        justifyContent: 'center',
        opacity: DESKTOP_SIDEBAR_CHROME_TOP_SETTINGS_ICON_OPACITY,
    },
    leftSidebarCollapseIcon: {
        transform: [{ translateY: 1 }, { scaleX: -1 }],
    },
    notificationButton: {
        position: 'relative',
    },
    topNotificationButton: {
        width: DESKTOP_SIDEBAR_CHROME_TOP_NAV_ICON_GLYPH_SIZE_PX,
        height: DESKTOP_SIDEBAR_CHROME_TOP_NAV_ICON_GLYPH_SIZE_PX,
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
    },
    badge: {
        position: 'absolute',
        top: -4,
        right: -4,
        backgroundColor: theme.colors.status.error,
        borderRadius: 8,
        minWidth: 16,
        height: 16,
        paddingHorizontal: 4,
        justifyContent: 'center',
        alignItems: 'center',
    },
    badgeText: {
        color: theme.colors.button.primary.tint,
        fontSize: 10,
        ...Typography.default('semiBold'),
    },
    indicatorDot: {
        position: 'absolute',
        top: 4,
        right: 2,
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: theme.colors.text.primary,
    },
    topIndicatorDot: {
        position: 'absolute',
        top: DESKTOP_SIDEBAR_CHROME_TOP_NOTIFICATION_DOT_TOP_PX,
        right: DESKTOP_SIDEBAR_CHROME_TOP_NOTIFICATION_DOT_RIGHT_PX,
        width: DESKTOP_SIDEBAR_CHROME_TOP_NOTIFICATION_DOT_SIZE_PX,
        height: DESKTOP_SIDEBAR_CHROME_TOP_NOTIFICATION_DOT_SIZE_PX,
        borderRadius: DESKTOP_SIDEBAR_CHROME_TOP_NOTIFICATION_DOT_SIZE_PX / 2,
        backgroundColor: theme.colors.text.primary,
    },
    windowControlsButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    windowControlsButtonsColumn: {
        flexDirection: 'column',
        alignItems: 'center',
        gap: 6,
    },
    windowControlsButton: {
        width: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX,
        height: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX,
        borderRadius: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX / 2,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.base,
    },
}));
