export const SPAWN_SESSION_ERROR_CODES = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_ENVIRONMENT_VARIABLES: 'INVALID_ENVIRONMENT_VARIABLES',
  AUTH_ENV_UNEXPANDED: 'AUTH_ENV_UNEXPANDED',
  RESUME_NOT_SUPPORTED: 'RESUME_NOT_SUPPORTED',
  RESUME_MISSING_ENCRYPTION_KEY: 'RESUME_MISSING_ENCRYPTION_KEY',
  RESUME_UNSUPPORTED_ENCRYPTION_VARIANT: 'RESUME_UNSUPPORTED_ENCRYPTION_VARIANT',
  DIRECTORY_CREATE_FAILED: 'DIRECTORY_CREATE_FAILED',
  SPAWN_VALIDATION_FAILED: 'SPAWN_VALIDATION_FAILED',
  SPAWN_NO_PID: 'SPAWN_NO_PID',
  CHILD_EXITED_BEFORE_WEBHOOK: 'CHILD_EXITED_BEFORE_WEBHOOK',
  SESSION_WEBHOOK_TIMEOUT: 'SESSION_WEBHOOK_TIMEOUT',
  ACCOUNT_SCOPE_CHANGED: 'ACCOUNT_SCOPE_CHANGED',
  SPAWN_FAILED: 'SPAWN_FAILED',
  DAEMON_RPC_UNAVAILABLE: 'DAEMON_RPC_UNAVAILABLE',
  UNEXPECTED: 'UNEXPECTED',
} as const;

export type SpawnSessionErrorCode = (typeof SPAWN_SESSION_ERROR_CODES)[keyof typeof SPAWN_SESSION_ERROR_CODES];

export type SpawnSessionResult =
  | { type: 'success'; sessionId?: string }
  | { type: 'requestToApproveDirectoryCreation'; directory: string }
  | { type: 'error'; errorCode: SpawnSessionErrorCode; errorMessage: string };
