import { describe, expect, it } from 'vitest';

import { extractCompactRow, extractRawRow } from './transcriptHistoryRows';

const localCommandArtifactRows = [
  {
    label: 'local command caveat',
    decrypted: {
      role: 'user',
      content: {
        type: 'text',
        text: '<local-command-caveat>Generated by a local command.</local-command-caveat>',
      },
    },
  },
  {
    label: 'compact command marker',
    decrypted: {
      role: 'user',
      content: {
        type: 'text',
        text: '<command-name>/compact</command-name>\n<command-message>compact</command-message>',
      },
    },
  },
  {
    label: 'compact hook stdout',
    decrypted: {
      role: 'user',
      content: {
        type: 'text',
        text: [
          '<local-command-stdout>Compacted',
          'PreCompact [/Users/test/.claude/hooks/pre-compact.sh] completed successfully',
          'PostCompact [/Users/test/.claude/hooks/post-compact.sh] completed successfully</local-command-stdout>',
        ].join('\n'),
      },
    },
  },
] as const;

const claudeConsumedMarkerArtifactRows = [
  {
    label: 'current Claude JSONL consumed progress marker',
    decrypted: {
      role: 'agent',
      content: {
        type: 'output',
        data: {
          type: 'progress',
          marker: 'claude_jsonl_consumed_marker',
          key: 'claude-message-key',
        },
      },
    },
  },
  {
    label: 'legacy Claude JSONL consumed marker',
    decrypted: {
      role: 'agent',
      content: {
        type: 'claude_jsonl_consumed_marker',
        key: 'claude-message-key',
      },
    },
  },
] as const;

describe('extractCompactRow', () => {
  it('extracts assistant text from output rows', () => {
    const row = extractCompactRow({
      createdAt: 1,
      fallbackId: '3',
      decrypted: {
        role: 'agent',
        content: {
          type: 'output',
          data: {
            type: 'assistant',
            message: {
              role: 'assistant',
              content: [{ type: 'text', text: 'OK' }],
            },
          },
        },
      },
    });

    expect(row).toMatchObject({
      id: '3',
      createdAt: 1,
      role: 'agent',
      kind: 'output',
      text: 'OK',
    });
  });

  it('extracts provider text from ACP message rows', () => {
    const row = extractCompactRow({
      createdAt: 1,
      fallbackId: '4',
      decrypted: {
        role: 'agent',
        content: {
          type: 'acp',
          provider: 'opencode',
          data: {
            type: 'message',
            message: 'provider compact text',
          },
        },
      },
    });

    expect(row).toMatchObject({
      id: '4',
      createdAt: 1,
      role: 'agent',
      kind: 'acp',
      text: 'provider compact text',
    });
  });

  it('does not emit compact rows for event-only provider payloads', () => {
    const row = extractCompactRow({
      createdAt: 1,
      fallbackId: '5',
      decrypted: {
        role: 'agent',
        content: {
          type: 'codex',
          provider: 'codex',
          data: {
            type: 'token_count',
            input_tokens: 10,
            output_tokens: 5,
          },
        },
      },
    });

    expect(row).toBeNull();
  });

  it('extracts visible session event message rows for compact history', () => {
    const row = extractCompactRow({
      createdAt: 1,
      fallbackId: 'event-message-1',
      decrypted: {
        role: 'agent',
        content: {
          type: 'event',
          data: {
            type: 'message',
            message: 'Claude unified terminal cannot start.',
          },
        },
      },
    });

    expect(row).toMatchObject({
      id: 'event-message-1',
      createdAt: 1,
      role: 'agent',
      kind: 'event',
      text: 'Claude unified terminal cannot start.',
    });
  });

  it.each(localCommandArtifactRows)('does not emit compact rows for persisted $label artifacts', ({ decrypted }) => {
    const row = extractCompactRow({
      createdAt: 1,
      fallbackId: 'local-command-artifact',
      decrypted,
    });

    expect(row).toBeNull();
  });

  it.each(claudeConsumedMarkerArtifactRows)('does not emit compact rows for persisted $label artifacts', ({ decrypted }) => {
    const row = extractCompactRow({
      createdAt: 1,
      fallbackId: 'claude-consumed-marker-artifact',
      decrypted,
    });

    expect(row).toBeNull();
  });

  it('extracts assistant text from Codex message rows', () => {
    const row = extractCompactRow({
      createdAt: 1,
      fallbackId: '6',
      decrypted: {
        role: 'agent',
        content: {
          type: 'codex',
          provider: 'codex',
          data: {
            type: 'message',
            message: 'codex provider text',
          },
        },
      },
    });

    expect(row).toMatchObject({
      id: '6',
      createdAt: 1,
      role: 'agent',
      kind: 'codex',
      text: 'codex provider text',
    });
  });
});

describe('extractRawRow', () => {
  it.each(localCommandArtifactRows)('does not emit raw rows for persisted $label artifacts', ({ decrypted }) => {
    const row = extractRawRow({
      createdAt: 1,
      fallbackId: 'local-command-artifact',
      decrypted,
      includeMeta: true,
      includeStructuredPayload: true,
    });

    expect(row).toBeNull();
  });

  it.each(claudeConsumedMarkerArtifactRows)('does not emit raw rows for persisted $label artifacts', ({ decrypted }) => {
    const row = extractRawRow({
      createdAt: 1,
      fallbackId: 'claude-consumed-marker-artifact',
      decrypted,
      includeMeta: true,
      includeStructuredPayload: true,
    });

    expect(row).toBeNull();
  });
});
