import { COMMUNITY_BUILT_IN_THEME_PROFILES } from './communityBuiltInThemeProfiles';
import { createBuiltInProfile } from './builtInThemeProfileFactory';
import type { BuiltInThemeProfileDefinition, BuiltInThemeProfilePresetId } from './themeProfileTypes';

export const BUILT_IN_THEME_PROFILES: readonly BuiltInThemeProfileDefinition[] = [
    {
        presetId: 'premiumDark',
        translationKey: 'settingsAppearance.themeProfiles.presets.premiumDark',
        preferredMode: 'dark',
        cloneable: true,
        editable: false,
        deletable: false,
        profile: createBuiltInProfile('premiumDark', 'Crisp Dark', {
            light: {},
            dark: {
                'background.canvas': '#050506',
                'surface.base': '#141417',
                'surface.inset': '#0D0D10',
                'surface.elevated': '#1B1B20',
                'surface.selected': '#26262D',
                'surface.pressed': '#2D2D35',
                'surface.pressedOverlay': 'rgba(255,255,255,0.07)',
                'surface.ripple': 'rgba(255,255,255,0.10)',
                'border.default': 'rgba(255,255,255,0.065)',
                'border.surface': 'rgba(255,255,255,0.075)',
                'border.strong': 'rgba(255,255,255,0.13)',
                'border.modal': 'rgba(255,255,255,0.10)',
                'effect.surfaceHighlight': 'rgba(255,255,255,0.055)',
                'chrome.header.background': '#141417',
                'chrome.header.foreground': '#ECECEF',
                'text.primary': '#ECECEF',
                'text.secondary': '#9A9AA3',
                'text.tertiary': '#6F6F78',
                'text.link': '#82A8FF',
                'text.destructive': '#E87878',
                'text.placeholder': '#6F6F78',
                'text.disabled': '#50515A',
                'state.active.background': 'rgba(78,116,190,0.18)',
                'state.active.border': 'rgba(100,145,230,0.45)',
                'state.active.foreground': '#DDE8FF',
                'state.success.foreground': '#70D98A',
                'state.success.background': 'rgba(112,217,138,0.12)',
                'state.success.border': 'rgba(112,217,138,0.30)',
                'state.warning.foreground': '#E6B84A',
                'state.warning.background': 'rgba(230,184,74,0.12)',
                'state.warning.border': 'rgba(230,184,74,0.30)',
                'state.danger.foreground': '#E87878',
                'state.danger.background': 'rgba(232,120,120,0.12)',
                'state.danger.border': 'rgba(232,120,120,0.30)',
                'state.info.foreground': '#82A8FF',
                'state.info.background': 'rgba(130,168,255,0.13)',
                'state.info.border': 'rgba(130,168,255,0.32)',
                'state.neutral.foreground': '#9A9AA3',
                'state.neutral.background': 'rgba(154,154,163,0.11)',
                'state.neutral.border': 'rgba(154,154,163,0.22)',
                'control.button.primary.background': '#24242B',
                'control.button.primary.foreground': '#ECECEF',
                'control.button.primary.disabled': '#2D2D35',
                'control.button.secondary.background': 'transparent',
                'control.button.secondary.foreground': '#ECECEF',
                'control.input.background': '#17171C',
                'control.input.foreground': '#ECECEF',
                'control.input.placeholder': '#6F6F78',
                'control.switch.track.active': '#5476BE',
                'control.switch.track.inactive': '#2D2D35',
                'control.switch.thumb.active': '#ECECEF',
                'control.switch.thumb.inactive': '#9A9AA3',
                'control.radio.active': '#82A8FF',
                'control.radio.inactive': '#6F6F78',
                'control.radio.dot': '#ECECEF',
                'control.segmentedControl.trackBackground': '#1B1B20',
                'control.segmentedControl.activeBackground': '#26262D',
                'control.fab.background': '#24242B',
                'control.fab.backgroundPressed': '#2D2D35',
                'control.fab.foreground': '#ECECEF',
                'control.permissionButton.allow.background': 'rgba(112,217,138,0.16)',
                'control.permissionButton.allow.foreground': '#70D98A',
                'control.permissionButton.deny.background': 'rgba(232,120,120,0.16)',
                'control.permissionButton.deny.foreground': '#E87878',
                'control.permissionButton.allowAll.background': 'rgba(130,168,255,0.16)',
                'control.permissionButton.allowAll.foreground': '#82A8FF',
                'control.permissionButton.inactive.background': '#1B1B20',
                'control.permissionButton.inactive.border': 'rgba(255,255,255,0.075)',
                'control.permissionButton.inactive.foreground': '#9A9AA3',
                'control.permissionButton.selected.background': '#26262D',
                'control.permissionButton.selected.border': 'rgba(255,255,255,0.13)',
                'control.permissionButton.selected.foreground': '#ECECEF',
                'message.user.background': '#24242B',
                'message.user.foreground': '#ECECEF',
                'message.agent.foreground': '#ECECEF',
                'message.event.foreground': '#9A9AA3',
                'syntax.keyword': '#82A8FF',
                'syntax.string': '#70D98A',
                'syntax.comment': '#6F6F78',
                'syntax.number': '#E6B84A',
                'syntax.function': '#B79CFF',
                'syntax.default': '#ECECEF',
                'versionControl.added.foreground': '#70D98A',
                'versionControl.removed.foreground': '#E87878',
                'versionControl.added.background': 'rgba(112,217,138,0.12)',
                'versionControl.removed.background': 'rgba(232,120,120,0.12)',
                'diff.added.background': 'rgba(112,217,138,0.12)',
                'diff.added.foreground': '#BFF0CB',
                'diff.removed.background': 'rgba(232,120,120,0.12)',
                'diff.removed.foreground': '#F3C2C2',
                'diff.hunk.background': 'rgba(130,168,255,0.13)',
                'diff.hunk.foreground': '#CAD8FF',
                'diff.context.foreground': '#9A9AA3',
                'diff.inlineAdded.background': 'rgba(112,217,138,0.18)',
                'diff.inlineAdded.foreground': '#D5F6DD',
                'diff.inlineRemoved.background': 'rgba(232,120,120,0.18)',
                'diff.inlineRemoved.foreground': '#F8D7D7',
                'permission.default': '#9A9AA3',
                'permission.acceptEdits': '#70D98A',
                'permission.bypass': '#E87878',
                'permission.plan': '#B79CFF',
                'permission.readOnly': '#82A8FF',
                'permission.safeYolo': '#E6B84A',
                'permission.yolo': '#E87878',
                'overlay.scrimSoft': 'rgba(0,0,0,0.46)',
                'overlay.scrim': 'rgba(0,0,0,0.66)',
                'overlay.scrimStrong': 'rgba(0,0,0,0.80)',
                'overlay.scrimWizard': 'rgba(0,0,0,0.72)',
                'overlay.foreground': '#ECECEF',
                'overlay.secondaryForeground': '#9A9AA3',
            },
        }),
    },
    {
        presetId: 'nightDark',
        translationKey: 'settingsAppearance.themeProfiles.presets.nightDark',
        preferredMode: 'dark',
        cloneable: true,
        editable: false,
        deletable: false,
        profile: createBuiltInProfile('nightDark', 'Night Dark', {
            light: {},
            dark: {
                'background.canvas': '#020204',
                'surface.base': '#090A0D',
                'surface.inset': '#050609',
                'surface.elevated': '#11131A',
                'surface.selected': '#181B25',
                'surface.pressed': '#202433',
                'surface.pressedOverlay': 'rgba(255,255,255,0.055)',
                'surface.ripple': 'rgba(255,255,255,0.085)',
                'border.default': 'rgba(255,255,255,0.055)',
                'border.surface': 'rgba(255,255,255,0.065)',
                'border.strong': 'rgba(255,255,255,0.11)',
                'border.modal': 'rgba(255,255,255,0.09)',
                'effect.surfaceHighlight': 'rgba(255,255,255,0.035)',
                'chrome.header.background': '#090A0D',
                'chrome.header.foreground': '#E8E8EA',
                'text.primary': '#E8E8EA',
                'text.secondary': '#8F9099',
                'text.tertiary': '#62636D',
                'text.link': '#F3D88B',
                'text.destructive': '#E07070',
                'text.placeholder': '#62636D',
                'text.disabled': '#454752',
                'state.active.background': 'rgba(245,158,66,0.13)',
                'state.active.border': 'rgba(245,190,90,0.34)',
                'state.active.foreground': '#F3D88B',
                'state.success.foreground': '#67D887',
                'state.success.background': 'rgba(103,216,135,0.11)',
                'state.success.border': 'rgba(103,216,135,0.26)',
                'state.warning.foreground': '#F3D88B',
                'state.warning.background': 'rgba(243,216,139,0.11)',
                'state.warning.border': 'rgba(243,216,139,0.26)',
                'state.danger.foreground': '#E07070',
                'state.danger.background': 'rgba(224,112,112,0.11)',
                'state.danger.border': 'rgba(224,112,112,0.26)',
                'state.info.foreground': '#A7B8FF',
                'state.info.background': 'rgba(167,184,255,0.11)',
                'state.info.border': 'rgba(167,184,255,0.25)',
                'state.neutral.foreground': '#8F9099',
                'state.neutral.background': 'rgba(143,144,153,0.10)',
                'state.neutral.border': 'rgba(143,144,153,0.19)',
                'control.button.primary.background': '#181B25',
                'control.button.primary.foreground': '#E8E8EA',
                'control.button.primary.disabled': '#202433',
                'control.button.secondary.background': 'transparent',
                'control.button.secondary.foreground': '#E8E8EA',
                'control.input.background': '#11131A',
                'control.input.foreground': '#E8E8EA',
                'control.input.placeholder': '#62636D',
                'control.switch.track.active': '#A76A2C',
                'control.switch.track.inactive': '#202433',
                'control.switch.thumb.active': '#F7E7BA',
                'control.switch.thumb.inactive': '#8F9099',
                'control.radio.active': '#F3D88B',
                'control.radio.inactive': '#62636D',
                'control.radio.dot': '#020204',
                'control.segmentedControl.trackBackground': '#11131A',
                'control.segmentedControl.activeBackground': '#181B25',
                'control.fab.background': '#181B25',
                'control.fab.backgroundPressed': '#202433',
                'control.fab.foreground': '#E8E8EA',
                'control.permissionButton.allow.background': 'rgba(103,216,135,0.14)',
                'control.permissionButton.allow.foreground': '#67D887',
                'control.permissionButton.deny.background': 'rgba(224,112,112,0.14)',
                'control.permissionButton.deny.foreground': '#E07070',
                'control.permissionButton.allowAll.background': 'rgba(243,216,139,0.14)',
                'control.permissionButton.allowAll.foreground': '#F3D88B',
                'control.permissionButton.inactive.background': '#11131A',
                'control.permissionButton.inactive.border': 'rgba(255,255,255,0.065)',
                'control.permissionButton.inactive.foreground': '#8F9099',
                'control.permissionButton.selected.background': '#181B25',
                'control.permissionButton.selected.border': 'rgba(255,255,255,0.11)',
                'control.permissionButton.selected.foreground': '#E8E8EA',
                'message.user.background': '#181B25',
                'message.user.foreground': '#E8E8EA',
                'message.agent.foreground': '#E8E8EA',
                'message.event.foreground': '#8F9099',
                'syntax.keyword': '#A7B8FF',
                'syntax.string': '#67D887',
                'syntax.comment': '#62636D',
                'syntax.number': '#F3D88B',
                'syntax.function': '#C0A7FF',
                'syntax.default': '#E8E8EA',
                'versionControl.added.foreground': '#67D887',
                'versionControl.removed.foreground': '#E07070',
                'versionControl.added.background': 'rgba(103,216,135,0.11)',
                'versionControl.removed.background': 'rgba(224,112,112,0.11)',
                'diff.added.background': 'rgba(103,216,135,0.11)',
                'diff.added.foreground': '#C8F2D3',
                'diff.removed.background': 'rgba(224,112,112,0.11)',
                'diff.removed.foreground': '#F1C6C6',
                'diff.hunk.background': 'rgba(243,216,139,0.10)',
                'diff.hunk.foreground': '#F7E7BA',
                'diff.context.foreground': '#8F9099',
                'diff.inlineAdded.background': 'rgba(103,216,135,0.16)',
                'diff.inlineAdded.foreground': '#D9F6E0',
                'diff.inlineRemoved.background': 'rgba(224,112,112,0.16)',
                'diff.inlineRemoved.foreground': '#F5D8D8',
                'permission.default': '#8F9099',
                'permission.acceptEdits': '#67D887',
                'permission.bypass': '#E07070',
                'permission.plan': '#C0A7FF',
                'permission.readOnly': '#A7B8FF',
                'permission.safeYolo': '#F3D88B',
                'permission.yolo': '#E07070',
                'overlay.scrimSoft': 'rgba(0,0,0,0.54)',
                'overlay.scrim': 'rgba(0,0,0,0.72)',
                'overlay.scrimStrong': 'rgba(0,0,0,0.86)',
                'overlay.scrimWizard': 'rgba(0,0,0,0.78)',
                'overlay.foreground': '#E8E8EA',
                'overlay.secondaryForeground': '#8F9099',
            },
        }),
    },
    ...COMMUNITY_BUILT_IN_THEME_PROFILES.slice(0, 7),
    {
        presetId: 'premiumLight',
        translationKey: 'settingsAppearance.themeProfiles.presets.premiumLight',
        preferredMode: 'light',
        cloneable: true,
        editable: false,
        deletable: false,
        profile: createBuiltInProfile('premiumLight', 'Crisp Light', {
            light: {
                'background.canvas': '#F6F6F4',
                'surface.base': '#FFFFFF',
                'surface.inset': '#F2F2F0',
                'surface.elevated': '#FCFCFC',
                'border.surface': 'rgba(0,0,0,0.08)',
                'border.strong': 'rgba(0,0,0,0.14)',
                'effect.surfaceHighlight': 'transparent',
                'text.primary': '#111114',
                'text.secondary': '#5A5A5F',
                'text.tertiary': '#7A7A80',
                'state.active.background': 'rgba(10,132,255,0.08)',
                'state.active.border': 'rgba(10,132,255,0.40)',
                'state.active.foreground': '#111114',
                'state.success.foreground': '#248A3D',
                'state.warning.foreground': '#B26A00',
                'state.danger.foreground': '#D70015',
                'state.info.foreground': '#0A84FF',
            },
            dark: {},
        }),
    },
    ...COMMUNITY_BUILT_IN_THEME_PROFILES.slice(7),
] as const;

export const getBuiltInThemeProfileDefinition = (presetId: BuiltInThemeProfilePresetId): BuiltInThemeProfileDefinition | undefined => (
    BUILT_IN_THEME_PROFILES.find((definition) => definition.presetId === presetId)
);

export const isBuiltInThemeProfilePresetId = (value: string | null | undefined): value is BuiltInThemeProfilePresetId => (
    typeof value === 'string' && BUILT_IN_THEME_PROFILES.some((definition) => definition.presetId === value)
);
