import { COMMUNITY_BUILT_IN_THEME_PROFILES } from './communityBuiltInThemeProfiles';
import { createBuiltInProfile } from './builtInThemeProfileFactory';
import { classicDarkProfile } from './classicDarkThemeProfile';
import { pitchDarkProfile, premiumDarkProfile, sunsetDarkProfile, tokyoNightProfile } from './builtInDarkThemeProfiles';
import type { BuiltInThemeProfileDefinition, BuiltInThemeProfilePresetId } from './themeProfileTypes';

export const BUILT_IN_THEME_PROFILES: readonly BuiltInThemeProfileDefinition[] = [
    {
        presetId: 'premiumDark',
        translationKey: 'settingsAppearance.themeProfiles.presets.premiumDark',
        preferredMode: 'dark',
        cloneable: true,
        editable: false,
        deletable: false,
        profile: premiumDarkProfile,
    },
    {
        presetId: 'pitchDark',
        translationKey: 'settingsAppearance.themeProfiles.presets.pitchDark',
        preferredMode: 'dark',
        cloneable: true,
        editable: false,
        deletable: false,
        profile: pitchDarkProfile,
    },
    {
        presetId: 'sunsetDark',
        translationKey: 'settingsAppearance.themeProfiles.presets.sunsetDark',
        preferredMode: 'dark',
        cloneable: true,
        editable: false,
        deletable: false,
        profile: sunsetDarkProfile,
    },
    {
        presetId: 'tokyoNight',
        translationKey: 'settingsAppearance.themeProfiles.presets.tokyoNight',
        preferredMode: 'dark',
        cloneable: true,
        editable: false,
        deletable: false,
        profile: tokyoNightProfile,
    },
    {
        presetId: 'nightDark',
        translationKey: 'settingsAppearance.themeProfiles.presets.nightDark',
        preferredMode: 'dark',
        cloneable: true,
        editable: false,
        deletable: false,
        profile: createBuiltInProfile('nightDark', 'Night Dark', 'dark', {
            light: {},
            dark: {
                'background.canvas': '#020204',
                'surface.base': '#090A0E',
                'surface.inset': '#050609',
                'surface.elevated': '#101116',
                'surface.selected': '#141620',
                'surface.pressed': '#191C28',
                'surface.pressedOverlay': 'rgba(255,255,255,0.045)',
                'surface.ripple': 'rgba(255,255,255,0.075)',
                'border.default': 'rgba(255,255,255,0.048)',
                'border.surface': 'rgba(255,255,255,0.055)',
                'border.strong': 'rgba(255,255,255,0.095)',
                'border.modal': 'rgba(255,255,255,0.08)',
                'effect.surfaceHighlight': 'rgba(255,255,255,0.028)',
                'chrome.header.background': '#090A0E',
                'chrome.header.foreground': '#E4E3E8',
                'text.primary': '#E4E3E8',
                'text.secondary': '#898892',
                'text.tertiary': '#5D5C66',
                'text.link': '#F3D88B',
                'text.destructive': '#E07070',
                'text.placeholder': '#55545E',
                'text.disabled': '#43444E',
                'state.active.background': 'rgba(225,151,63,0.10)',
                'state.active.border': 'rgba(225,177,90,0.26)',
                'state.active.foreground': '#E8C46F',
                'state.success.foreground': '#67D887',
                'state.success.background': 'rgba(103,216,135,0.11)',
                'state.success.border': 'rgba(103,216,135,0.26)',
                'state.warning.foreground': '#E8C46F',
                'state.warning.background': 'rgba(232,196,111,0.10)',
                'state.warning.border': 'rgba(232,196,111,0.24)',
                'state.danger.foreground': '#E07070',
                'state.danger.background': 'rgba(224,112,112,0.11)',
                'state.danger.border': 'rgba(224,112,112,0.26)',
                'state.info.foreground': '#9EAAE8',
                'state.info.background': 'rgba(158,170,232,0.10)',
                'state.info.border': 'rgba(158,170,232,0.23)',
                'state.neutral.foreground': '#898892',
                'state.neutral.background': 'rgba(137,136,146,0.09)',
                'state.neutral.border': 'rgba(137,136,146,0.17)',
                'control.button.primary.background': '#141620',
                'control.button.primary.foreground': '#E4E3E8',
                'control.button.primary.disabled': '#191C28',
                'control.button.secondary.background': 'transparent',
                'control.button.secondary.foreground': '#E4E3E8',
                'control.input.background': '#0D0E14',
                'control.input.foreground': '#E4E3E8',
                'control.input.placeholder': '#55545E',
                'control.switch.track.active': '#8E5B26',
                'control.switch.track.inactive': '#191C28',
                'control.switch.thumb.active': '#E8C46F',
                'control.switch.thumb.inactive': '#898892',
                'control.radio.active': '#E8C46F',
                'control.radio.inactive': '#5D5C66',
                'control.radio.dot': '#020204',
                'control.segmentedControl.trackBackground': '#0D0E14',
                'control.segmentedControl.activeBackground': '#141620',
                'control.fab.background': '#141620',
                'control.fab.backgroundPressed': '#191C28',
                'control.fab.foreground': '#E4E3E8',
                'control.permissionButton.allow.background': 'rgba(103,216,135,0.14)',
                'control.permissionButton.allow.foreground': '#67D887',
                'control.permissionButton.deny.background': 'rgba(224,112,112,0.14)',
                'control.permissionButton.deny.foreground': '#E07070',
                'control.permissionButton.allowAll.background': 'rgba(243,216,139,0.14)',
                'control.permissionButton.allowAll.foreground': '#F3D88B',
                'control.permissionButton.inactive.background': '#0D0E14',
                'control.permissionButton.inactive.border': 'rgba(255,255,255,0.055)',
                'control.permissionButton.inactive.foreground': '#898892',
                'control.permissionButton.selected.background': '#141620',
                'control.permissionButton.selected.border': 'rgba(255,255,255,0.095)',
                'control.permissionButton.selected.foreground': '#E4E3E8',
                'message.user.background': '#141620',
                'message.user.foreground': '#E4E3E8',
                'message.agent.foreground': '#E4E3E8',
                'message.event.foreground': '#898892',
                'syntax.keyword': '#9EAAE8',
                'syntax.string': '#67D887',
                'syntax.comment': '#5D5C66',
                'syntax.number': '#E8C46F',
                'syntax.function': '#C0A7FF',
                'syntax.default': '#E4E3E8',
                'versionControl.added.foreground': '#67D887',
                'versionControl.removed.foreground': '#E07070',
                'versionControl.added.background': 'rgba(103,216,135,0.11)',
                'versionControl.removed.background': 'rgba(224,112,112,0.11)',
                'diff.added.background': 'rgba(103,216,135,0.11)',
                'diff.added.foreground': '#C8F2D3',
                'diff.removed.background': 'rgba(224,112,112,0.11)',
                'diff.removed.foreground': '#F1C6C6',
                'diff.hunk.background': 'rgba(232,196,111,0.09)',
                'diff.hunk.foreground': '#E8C46F',
                'diff.context.foreground': '#898892',
                'diff.inlineAdded.background': 'rgba(103,216,135,0.16)',
                'diff.inlineAdded.foreground': '#D9F6E0',
                'diff.inlineRemoved.background': 'rgba(224,112,112,0.16)',
                'diff.inlineRemoved.foreground': '#F5D8D8',
                'permission.default': '#898892',
                'permission.acceptEdits': '#67D887',
                'permission.bypass': '#E07070',
                'permission.plan': '#C0A7FF',
                'permission.readOnly': '#9EAAE8',
                'permission.safeYolo': '#E8C46F',
                'permission.yolo': '#E07070',
                'overlay.scrimSoft': 'rgba(0,0,0,0.54)',
                'overlay.scrim': 'rgba(0,0,0,0.72)',
                'overlay.scrimStrong': 'rgba(0,0,0,0.86)',
                'overlay.scrimWizard': 'rgba(0,0,0,0.78)',
                'overlay.foreground': '#E4E3E8',
                'overlay.secondaryForeground': '#898892',
            },
        }),
    },
    {
        presetId: 'classicDark',
        translationKey: 'settingsAppearance.themeProfiles.presets.classicDark',
        preferredMode: 'dark',
        cloneable: true,
        editable: false,
        deletable: false,
        profile: classicDarkProfile,
    },
    ...COMMUNITY_BUILT_IN_THEME_PROFILES.slice(0, 8),
    {
        presetId: 'premiumLight',
        translationKey: 'settingsAppearance.themeProfiles.presets.premiumLight',
        preferredMode: 'light',
        cloneable: true,
        editable: false,
        deletable: false,
        profile: createBuiltInProfile('premiumLight', 'Crisp Light', 'light', {
            light: {
                'background.canvas': '#F6F6F4',
                'surface.base': '#FFFFFF',
                'surface.inset': '#F2F2F0',
                'surface.elevated': '#FCFCFC',
                'border.surface': 'rgba(0,0,0,0.08)',
                'border.strong': 'rgba(0,0,0,0.14)',
                'effect.surfaceHighlight': 'transparent',
                'text.primary': '#111114',
                'text.secondary': '#5A5A5F',
                'text.tertiary': '#7A7A80',
                'state.active.background': 'rgba(10,132,255,0.08)',
                'state.active.border': 'rgba(10,132,255,0.40)',
                'state.active.foreground': '#111114',
                'state.success.foreground': '#248A3D',
                'state.warning.foreground': '#B26A00',
                'state.danger.foreground': '#D70015',
                'state.info.foreground': '#0A84FF',
            },
            dark: {},
        }),
    },
    ...COMMUNITY_BUILT_IN_THEME_PROFILES.slice(8),
] as const;

export const getBuiltInThemeProfileDefinition = (presetId: BuiltInThemeProfilePresetId): BuiltInThemeProfileDefinition | undefined => (
    BUILT_IN_THEME_PROFILES.find((definition) => definition.presetId === presetId)
);

export const isBuiltInThemeProfilePresetId = (value: string | null | undefined): value is BuiltInThemeProfilePresetId => (
    typeof value === 'string' && BUILT_IN_THEME_PROFILES.some((definition) => definition.presetId === value)
);
