import { Platform } from 'react-native';

import { createBuiltInProfile } from './builtInThemeProfileFactory';

export const classicDarkProfile = createBuiltInProfile('classicDark', 'Classic Dark', 'dark', {
    light: {},
    dark: {
        'background.canvas': '#181818',
        'surface.base': '#202020',
        'surface.inset': '#171717',
        'surface.elevated': '#292929',
        'surface.ripple': 'rgba(255, 255, 255, 0.08)',
        'surface.pressed': '#2C2C2C',
        'surface.selected': '#2C2C2C',
        'surface.pressedOverlay': Platform.select({ ios: '#2C2C2C', default: 'transparent' }),
        'border.default': '#292929',
        'border.surface': 'transparent',
        'border.strong': '#3a3a3a',
        'border.modal': 'rgba(255, 255, 255, 0.1)',
        'effect.surfaceHighlight': 'transparent',
        'chrome.header.background': '#202020',
        'chrome.header.foreground': '#ffffff',
        'text.primary': '#ffffff',
        'text.secondary': '#99999d',
        'text.tertiary': '#747478',
        'text.link': '#2BACCC',
        'text.destructive': '#FF453A',
        'text.placeholder': '#8E8E93',
        'text.disabled': '#48484A',
        'state.success.foreground': '#32D74B',
        'state.success.background': 'rgba(50, 215, 75, 0.15)',
        'state.success.border': '#32D74B',
        'state.warning.foreground': '#FF9F0A',
        'state.warning.background': 'rgba(255, 159, 10, 0.15)',
        'state.warning.border': '#FF9F0A',
        'state.danger.foreground': '#FF453A',
        'state.danger.background': 'rgba(255, 69, 58, 0.15)',
        'state.danger.border': '#FF453A',
        'state.info.foreground': '#9FA8DA',
        'state.info.background': 'rgba(10, 132, 255, 0.14)',
        'state.info.border': '#0A84FF',
        'state.neutral.foreground': '#8E8E93',
        'state.neutral.background': '#2C2C2E',
        'state.neutral.border': '#38383A',
        'state.active.foreground': '#0A84FF',
        'state.active.background': 'rgba(10, 132, 255, 0.12)',
        'state.active.border': 'rgba(10, 132, 255, 0.55)',
        'control.switch.track.active': '#1976D2',
        'control.switch.track.inactive': '#3a393f',
        'control.switch.thumb.active': '#FFFFFF',
        'control.switch.thumb.inactive': '#767577',
        'control.radio.active': '#0A84FF',
        'control.radio.inactive': '#48484A',
        'control.radio.dot': '#0A84FF',
        'control.segmentedControl.trackBackground': '#292929',
        'control.segmentedControl.activeBackground': '#202020',
        'control.fab.background': '#303030',
        'control.fab.backgroundPressed': '#1b1b1b',
        'control.fab.foreground': '#ffffff',
        'control.button.primary.background': '#1b1b1b',
        'control.button.primary.foreground': '#FFFFFF',
        'control.button.primary.disabled': '#C0C0C0',
        'control.button.secondary.background': 'transparent',
        'control.button.secondary.foreground': '#8E8E93',
        'control.input.background': '#303030',
        'control.input.foreground': '#FFFFFF',
        'control.input.placeholder': '#8E8E93',
        'control.permissionButton.allow.background': '#32D74B',
        'control.permissionButton.allow.foreground': '#FFFFFF',
        'control.permissionButton.deny.background': '#FF453A',
        'control.permissionButton.deny.foreground': '#FFFFFF',
        'control.permissionButton.allowAll.background': '#0A84FF',
        'control.permissionButton.allowAll.foreground': '#FFFFFF',
        'control.permissionButton.inactive.background': '#2C2C2E',
        'control.permissionButton.inactive.border': '#38383A',
        'control.permissionButton.inactive.foreground': '#8E8E93',
        'control.permissionButton.selected.background': '#1C1C1E',
        'control.permissionButton.selected.border': '#38383A',
        'control.permissionButton.selected.foreground': '#FFFFFF',
        'message.user.background': '#2C2C2C',
        'message.user.foreground': '#FFFFFF',
        'message.agent.foreground': '#FFFFFF',
        'message.event.foreground': '#8E8E93',
        'syntax.keyword': '#569CD6',
        'syntax.string': '#CE9178',
        'syntax.comment': '#6A9955',
        'syntax.number': '#B5CEA8',
        'syntax.function': '#DCDCAA',
        'syntax.bracket1': '#FFD700',
        'syntax.bracket2': '#DA70D6',
        'syntax.bracket3': '#179FFF',
        'syntax.bracket4': '#FF8C00',
        'syntax.bracket5': '#00FF00',
        'syntax.default': '#D4D4D4',
        'versionControl.added.foreground': '#34C759',
        'versionControl.added.background': 'rgba(52, 199, 89, 0.15)',
        'versionControl.removed.foreground': '#FF453A',
        'versionControl.removed.background': 'rgba(255, 69, 58, 0.15)',
        'diff.outline': '#30363D',
        'diff.success': '#3FB950',
        'diff.error': '#F85149',
        'diff.added.background': '#0D2E1F',
        'diff.added.border': '#3FB950',
        'diff.added.foreground': '#C9D1D9',
        'diff.removed.background': '#3F1B23',
        'diff.removed.border': '#F85149',
        'diff.removed.foreground': '#C9D1D9',
        'diff.context.background': '#161B22',
        'diff.context.foreground': '#8B949E',
        'diff.lineNumber.background': '#161B22',
        'diff.lineNumber.foreground': '#6E7681',
        'diff.hunk.background': '#161B22',
        'diff.hunk.foreground': '#58A6FF',
        'diff.leadingSpaceDot': '#2A2A2A',
        'diff.inlineAdded.background': '#2A5A2A',
        'diff.inlineAdded.foreground': '#7AFF7A',
        'diff.inlineRemoved.background': '#5A2A2A',
        'diff.inlineRemoved.foreground': '#FF7A7A',
        'permission.default': '#8E8E93',
        'permission.acceptEdits': '#0A84FF',
        'permission.bypass': '#FF9F0A',
        'permission.plan': '#32D74B',
        'permission.readOnly': '#98989D',
        'permission.safeYolo': '#FF7A4C',
        'permission.yolo': '#FF453A',
        'overlay.scrimSoft': 'rgba(0, 0, 0, 0.45)',
        'overlay.scrim': 'rgba(0, 0, 0, 0.45)',
        'overlay.scrimStrong': 'rgba(0, 0, 0, 0.58)',
        'overlay.scrimWizard': 'rgba(0, 0, 0, 0.42)',
        'overlay.foreground': '#FFFFFF',
        'overlay.secondaryForeground': 'rgba(255, 255, 255, 0.9)',
    },
});
