export const THEME_PROFILE_SCHEMA_VERSION = 1 as const;
export const THEME_PROFILE_EXPORT_KIND = 'happier.themeProfile' as const;
export const THEME_PROFILE_MAX_JSON_BYTES = 64 * 1024;
export const THEME_PROFILE_MAX_PROFILES = 50;
export const THEME_PROFILE_MAX_OVERRIDES_PER_MODE = 300;
export const THEME_PROFILE_NAME_MAX_LENGTH = 64;
export const THEME_PROFILE_ID_PREFIX = 'theme_';
export const THEME_PROFILE_ID_MAX_LENGTH = 96;
export const DEFAULT_IMPORTED_THEME_PROFILE_NAME = 'Imported theme';
