import type { AIBackendProfile } from './backendProfileSchema.js';

const BUILT_IN_PROFILE_VERSION = '1.0.0';

export const DEFAULT_BUILT_IN_BACKEND_PROFILES: ReadonlyArray<AIBackendProfile> = [
  {
    id: 'anthropic',
    name: 'Anthropic (Default)',
    authMode: 'machineLogin',
    requiresMachineLoginTargetKey: 'agent:claude',
    environmentVariables: [],
    defaultPermissionModeByTargetKey: { 'agent:claude': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': true, 'agent:codex': false, 'agent:gemini': false },
    compatibility: {},
    envVarRequirements: [],
    isBuiltIn: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_PROFILE_VERSION,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek (Reasoner)',
    envVarRequirements: [{ name: 'DEEPSEEK_AUTH_TOKEN', kind: 'secret', required: true }],
    environmentVariables: [
      { name: 'ANTHROPIC_BASE_URL', value: '${DEEPSEEK_BASE_URL:-https://api.deepseek.com/anthropic}' },
      { name: 'ANTHROPIC_AUTH_TOKEN', value: '${DEEPSEEK_AUTH_TOKEN}' },
      { name: 'API_TIMEOUT_MS', value: '${DEEPSEEK_API_TIMEOUT_MS:-600000}' },
      { name: 'ANTHROPIC_MODEL', value: '${DEEPSEEK_MODEL:-deepseek-reasoner}' },
      { name: 'ANTHROPIC_SMALL_FAST_MODEL', value: '${DEEPSEEK_SMALL_FAST_MODEL:-deepseek-chat}' },
      { name: 'CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC', value: '${DEEPSEEK_CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC:-1}' },
    ],
    defaultPermissionModeByTargetKey: { 'agent:claude': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': true, 'agent:codex': false, 'agent:gemini': false },
    compatibility: {},
    isBuiltIn: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_PROFILE_VERSION,
  },
  {
    id: 'zai',
    name: 'Z.AI (GLM-4.6)',
    envVarRequirements: [{ name: 'Z_AI_AUTH_TOKEN', kind: 'secret', required: true }],
    environmentVariables: [
      { name: 'ANTHROPIC_BASE_URL', value: '${Z_AI_BASE_URL:-https://api.z.ai/api/anthropic}' },
      { name: 'ANTHROPIC_AUTH_TOKEN', value: '${Z_AI_AUTH_TOKEN}' },
      { name: 'API_TIMEOUT_MS', value: '${Z_AI_API_TIMEOUT_MS:-3000000}' },
      { name: 'ANTHROPIC_MODEL', value: '${Z_AI_MODEL:-GLM-4.6}' },
      { name: 'ANTHROPIC_DEFAULT_OPUS_MODEL', value: '${Z_AI_OPUS_MODEL:-GLM-4.6}' },
      { name: 'ANTHROPIC_DEFAULT_SONNET_MODEL', value: '${Z_AI_SONNET_MODEL:-GLM-4.6}' },
      { name: 'ANTHROPIC_DEFAULT_HAIKU_MODEL', value: '${Z_AI_HAIKU_MODEL:-GLM-4.5-Air}' },
    ],
    defaultPermissionModeByTargetKey: { 'agent:claude': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': true, 'agent:codex': false, 'agent:gemini': false },
    compatibility: {},
    isBuiltIn: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_PROFILE_VERSION,
  },
  {
    id: 'codex',
    name: 'Codex (Default)',
    authMode: 'machineLogin',
    requiresMachineLoginTargetKey: 'agent:codex',
    environmentVariables: [],
    defaultPermissionModeByTargetKey: { 'agent:codex': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': false, 'agent:codex': true, 'agent:gemini': false },
    compatibility: {},
    envVarRequirements: [],
    isBuiltIn: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_PROFILE_VERSION,
  },
  {
    id: 'openai',
    name: 'OpenAI (GPT-5)',
    envVarRequirements: [{ name: 'OPENAI_API_KEY', kind: 'secret', required: true }],
    environmentVariables: [
      { name: 'OPENAI_BASE_URL', value: 'https://api.openai.com/v1' },
      { name: 'OPENAI_MODEL', value: 'gpt-5-codex-high' },
      { name: 'OPENAI_API_TIMEOUT_MS', value: '600000' },
      { name: 'OPENAI_SMALL_FAST_MODEL', value: 'gpt-5-codex-low' },
      { name: 'API_TIMEOUT_MS', value: '600000' },
      { name: 'CODEX_SMALL_FAST_MODEL', value: 'gpt-5-codex-low' },
    ],
    defaultPermissionModeByTargetKey: { 'agent:codex': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': false, 'agent:codex': true, 'agent:gemini': false },
    compatibility: {},
    isBuiltIn: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_PROFILE_VERSION,
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    envVarRequirements: [{ name: 'AZURE_OPENAI_API_KEY', kind: 'secret', required: true }],
    environmentVariables: [
      { name: 'AZURE_OPENAI_API_VERSION', value: '2024-02-15-preview' },
      { name: 'OPENAI_API_TIMEOUT_MS', value: '600000' },
      { name: 'API_TIMEOUT_MS', value: '600000' },
    ],
    defaultPermissionModeByTargetKey: { 'agent:codex': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': false, 'agent:codex': true, 'agent:gemini': false },
    compatibility: {},
    isBuiltIn: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_PROFILE_VERSION,
  },
  {
    id: 'gemini',
    name: 'Gemini (Default)',
    authMode: 'machineLogin',
    requiresMachineLoginTargetKey: 'agent:gemini',
    environmentVariables: [],
    defaultPermissionModeByTargetKey: { 'agent:gemini': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': false, 'agent:codex': false, 'agent:gemini': true },
    compatibility: {},
    envVarRequirements: [],
    isBuiltIn: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_PROFILE_VERSION,
  },
  {
    id: 'gemini-api-key',
    name: 'Gemini (API key)',
    envVarRequirements: [{ name: 'GEMINI_API_KEY', kind: 'secret', required: true }],
    environmentVariables: [{ name: 'GEMINI_MODEL', value: 'gemini-2.5-pro' }],
    defaultPermissionModeByTargetKey: { 'agent:gemini': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': false, 'agent:codex': false, 'agent:gemini': true },
    compatibility: {},
    isBuiltIn: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_PROFILE_VERSION,
  },
  {
    id: 'gemini-vertex',
    name: 'Gemini (Vertex AI)',
    envVarRequirements: [
      { name: 'GOOGLE_CLOUD_PROJECT', kind: 'config', required: true },
      { name: 'GOOGLE_CLOUD_LOCATION', kind: 'config', required: true },
    ],
    environmentVariables: [
      { name: 'GOOGLE_GENAI_USE_VERTEXAI', value: '1' },
      { name: 'GEMINI_MODEL', value: 'gemini-2.5-pro' },
    ],
    defaultPermissionModeByTargetKey: { 'agent:gemini': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': false, 'agent:codex': false, 'agent:gemini': true },
    compatibility: {},
    isBuiltIn: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_PROFILE_VERSION,
  },
] as const;

export function getBuiltInBackendProfile(id: string): AIBackendProfile | null {
  const normalized = typeof id === 'string' ? id.trim() : '';
  if (!normalized) return null;
  return DEFAULT_BUILT_IN_BACKEND_PROFILES.find((p) => p.id === normalized) ?? null;
}
